// Package validate implements JSON Schema (Draft 7) validation and default
// injection for MCP tool arguments.
//
// The primary entry points are Validate, which checks a decoded JSON map
// against a schema produced by the schema package, and ApplyDefaults, which
// fills in missing fields from their schema-declared default values before
// validation runs.
//
// All error messages use field paths in dot-notation (e.g. "options.limit")
// so callers can surface actionable messages to the MCP client.
package validate

import (
	"fmt"
	"math"
	"regexp"
	"strings"
)

// ValidationError represents a single validation failure with a dot-separated
// field path and a human-readable message.
type ValidationError struct {
	Field   string // field path e.g. "query" or "options.limit"
	Message string // human-readable message
}

// Error implements the error interface, returning the human-readable message.
func (e *ValidationError) Error() string {
	return e.Message
}

// ValidationErrors is a slice of ValidationError values collected during a
// single Validate call. It implements the error interface by joining all
// messages with a semicolon.
type ValidationErrors []ValidationError

// Error implements the error interface. Multiple validation errors are joined
// with "; " so the result is a single, readable line.
func (e ValidationErrors) Error() string {
	if len(e) == 0 {
		return ""
	}
	msgs := make([]string, len(e))
	for i, err := range e {
		msgs[i] = err.Message
	}
	return strings.Join(msgs, "; ")
}

// Validate checks data against a JSON Schema and returns validation errors.
// schema is a map[string]any representing JSON Schema (as generated by schema.Generate).
// data is the parsed JSON input (map[string]any).
// Returns nil if there are no validation errors.
func Validate(schema map[string]any, data map[string]any) ValidationErrors {
	var errs ValidationErrors
	validateObject(schema, data, "", &errs)
	if len(errs) == 0 {
		return nil
	}
	return errs
}

// ApplyDefaults fills in default values from the schema for missing fields.
// Modifies data in-place and returns it.
func ApplyDefaults(schema map[string]any, data map[string]any) map[string]any {
	if data == nil {
		data = make(map[string]any)
	}
	applyDefaultsObject(schema, data)
	return data
}

// validateObject validates a data map against a schema object, appending errors
// to errs. prefix is the dot-separated path of the current object (empty at root).
func validateObject(schema map[string]any, data map[string]any, prefix string, errs *ValidationErrors) {
	// 1. Required fields
	if required, ok := schema["required"]; ok {
		if requiredList, ok := required.([]any); ok {
			for _, req := range requiredList {
				fieldName, ok := req.(string)
				if !ok {
					continue
				}
				if _, exists := data[fieldName]; !exists {
					path := fieldPath(prefix, fieldName)
					*errs = append(*errs, ValidationError{
						Field:   path,
						Message: fmt.Sprintf("field '%s' is required", path),
					})
				}
			}
		}
	}

	// 2. Validate each property present in data or defined in schema properties
	properties, _ := schema["properties"].(map[string]any)
	if properties == nil {
		return
	}

	for propName, propSchemaRaw := range properties {
		propSchema, ok := propSchemaRaw.(map[string]any)
		if !ok {
			continue
		}

		path := fieldPath(prefix, propName)
		value, exists := data[propName]
		if !exists {
			// Field absent — required check already handled above.
			continue
		}

		validateValue(propSchema, value, path, errs)
	}
}

// validateValue validates a single value against its schema, recursing as needed.
func validateValue(schema map[string]any, value any, path string, errs *ValidationErrors) {
	// Type checking
	if typVal, ok := schema["type"]; ok {
		typStr, ok := typVal.(string)
		if ok {
			if typeErr := checkType(typStr, value, path); typeErr != nil {
				*errs = append(*errs, *typeErr)
				// For type mismatches we still try enum/min/max checks where possible,
				// but skip recursive structural checks that rely on the correct type.
			} else {
				// Only recurse into structural checks when the type is correct.
				switch typStr {
				case "object":
					nested, ok := value.(map[string]any)
					if ok {
						validateObject(schema, nested, path, errs)
					}
				case "array":
					arr, ok := value.([]any)
					if ok {
						validateArrayItems(schema, arr, path, errs)
					}
				}
			}
		}
	}

	// Enum
	if enumRaw, ok := schema["enum"]; ok {
		if enumList, ok := enumRaw.([]any); ok {
			checkEnum(enumList, value, path, errs)
		}
	}

	// Minimum / Maximum (numbers)
	checkMinMax(schema, value, path, errs)

	// Pattern (strings)
	if patternRaw, ok := schema["pattern"]; ok {
		if patternStr, ok := patternRaw.(string); ok {
			if strVal, ok := value.(string); ok {
				checkPattern(patternStr, strVal, path, errs)
			}
		}
	}
}

// checkType returns a ValidationError if value does not match the expected JSON
// Schema type string, or nil if it does.
func checkType(typStr string, value any, path string) *ValidationError {
	var ok bool
	var gotType string

	switch typStr {
	case "string":
		_, ok = value.(string)
		if !ok {
			gotType = goTypeName(value)
		}
	case "boolean":
		_, ok = value.(bool)
		if !ok {
			gotType = goTypeName(value)
		}
	case "integer":
		ok = isInteger(value)
		if !ok {
			gotType = goTypeName(value)
		}
	case "number":
		ok = isNumber(value)
		if !ok {
			gotType = goTypeName(value)
		}
	case "array":
		_, ok = value.([]any)
		if !ok {
			gotType = goTypeName(value)
		}
	case "object":
		_, ok = value.(map[string]any)
		if !ok {
			gotType = goTypeName(value)
		}
	default:
		// Unknown type — pass through.
		return nil
	}

	if ok {
		return nil
	}
	return &ValidationError{
		Field:   path,
		Message: fmt.Sprintf("field '%s' must be %s %s, got %s", path, article(typStr), typStr, gotType),
	}
}

// checkEnum verifies that value is one of the listed enum values.
func checkEnum(enumList []any, value any, path string, errs *ValidationErrors) {
	for _, allowed := range enumList {
		if jsonEqual(allowed, value) {
			return
		}
	}

	// Format the allowed values list.
	strs := make([]string, len(enumList))
	for i, v := range enumList {
		strs[i] = fmt.Sprintf("%v", v)
	}
	*errs = append(*errs, ValidationError{
		Field:   path,
		Message: fmt.Sprintf("field '%s' must be one of [%s], got '%v'", path, strings.Join(strs, ", "), value),
	})
}

// checkMinMax validates numeric minimum and maximum constraints.
func checkMinMax(schema map[string]any, value any, path string, errs *ValidationErrors) {
	f, ok := toFloat64(value)
	if !ok {
		return
	}

	if minRaw, exists := schema["minimum"]; exists {
		if minF, ok := toFloat64(minRaw); ok {
			if f < minF {
				*errs = append(*errs, ValidationError{
					Field:   path,
					Message: fmt.Sprintf("field '%s' must be >= %s, got %s", path, formatNumber(minF), formatNumber(f)),
				})
			}
		}
	}

	if maxRaw, exists := schema["maximum"]; exists {
		if maxF, ok := toFloat64(maxRaw); ok {
			if f > maxF {
				*errs = append(*errs, ValidationError{
					Field:   path,
					Message: fmt.Sprintf("field '%s' must be <= %s, got %s", path, formatNumber(maxF), formatNumber(f)),
				})
			}
		}
	}
}

// checkPattern validates a string value against a regex pattern.
func checkPattern(pattern, value, path string, errs *ValidationErrors) {
	re, err := regexp.Compile(pattern)
	if err != nil {
		// Treat an invalid regex as no constraint rather than crashing.
		return
	}
	if !re.MatchString(value) {
		*errs = append(*errs, ValidationError{
			Field:   path,
			Message: fmt.Sprintf("field '%s' must match pattern %s", path, pattern),
		})
	}
}

// validateArrayItems validates each element of arr against the "items" sub-schema.
func validateArrayItems(schema map[string]any, arr []any, path string, errs *ValidationErrors) {
	itemsRaw, ok := schema["items"]
	if !ok {
		return
	}
	itemSchema, ok := itemsRaw.(map[string]any)
	if !ok {
		return
	}
	for i, item := range arr {
		itemPath := fmt.Sprintf("%s[%d]", path, i)
		validateValue(itemSchema, item, itemPath, errs)
	}
}

// applyDefaultsObject walks schema properties and fills missing fields in data
// from their "default" values, recursing into nested objects.
func applyDefaultsObject(schema map[string]any, data map[string]any) {
	properties, ok := schema["properties"].(map[string]any)
	if !ok {
		return
	}

	for propName, propSchemaRaw := range properties {
		propSchema, ok := propSchemaRaw.(map[string]any)
		if !ok {
			continue
		}

		existing, exists := data[propName]
		if !exists {
			if defaultVal, hasDefault := propSchema["default"]; hasDefault {
				data[propName] = defaultVal
			}
			// If no default, leave the field absent.
			continue
		}

		// Recurse into nested objects even when the field is already present.
		if nested, ok := existing.(map[string]any); ok {
			applyDefaultsObject(propSchema, nested)
		}
	}
}

// --- helpers -----------------------------------------------------------------

// fieldPath constructs a dot-separated field path from a prefix and field name.
func fieldPath(prefix, field string) string {
	if prefix == "" {
		return field
	}
	return prefix + "." + field
}

// isInteger returns true if v is an integer value (float64 with no fractional
// part, or a native Go integer type).
func isInteger(v any) bool {
	switch val := v.(type) {
	case float64:
		return val == math.Trunc(val) && !math.IsInf(val, 0) && !math.IsNaN(val)
	case int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64:
		return true
	}
	return false
}

// isNumber returns true if v is any numeric type.
func isNumber(v any) bool {
	switch v.(type) {
	case float64, float32,
		int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64:
		return true
	}
	return false
}

// toFloat64 converts common numeric types to float64.
func toFloat64(v any) (float64, bool) {
	switch val := v.(type) {
	case float64:
		return val, true
	case float32:
		return float64(val), true
	case int:
		return float64(val), true
	case int8:
		return float64(val), true
	case int16:
		return float64(val), true
	case int32:
		return float64(val), true
	case int64:
		return float64(val), true
	case uint:
		return float64(val), true
	case uint8:
		return float64(val), true
	case uint16:
		return float64(val), true
	case uint32:
		return float64(val), true
	case uint64:
		return float64(val), true
	}
	return 0, false
}

// jsonEqual compares two values for equality the way JSON unmarshalling would.
// Both sides may be float64, string, bool, or nil.
func jsonEqual(a, b any) bool {
	// Fast path: identical types.
	if fmt.Sprintf("%T", a) == fmt.Sprintf("%T", b) {
		return fmt.Sprintf("%v", a) == fmt.Sprintf("%v", b)
	}
	// Cross-type numeric equality (e.g. int(1) == float64(1)).
	fa, aIsNum := toFloat64(a)
	fb, bIsNum := toFloat64(b)
	if aIsNum && bIsNum {
		return fa == fb
	}
	return false
}

// goTypeName returns a concise, schema-friendly type name for a Go value.
func goTypeName(v any) string {
	switch v.(type) {
	case string:
		return "string"
	case bool:
		return "boolean"
	case float64, float32:
		return "number"
	case int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64:
		return "integer"
	case []any:
		return "array"
	case map[string]any:
		return "object"
	case nil:
		return "null"
	}
	return fmt.Sprintf("%T", v)
}

// article returns "a" or "an" depending on the first letter of the word.
func article(word string) string {
	if len(word) == 0 {
		return "a"
	}
	switch word[0] {
	case 'a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U':
		return "an"
	}
	return "a"
}

// formatNumber formats a float64 as an integer string when it has no fractional
// part, and as a decimal otherwise — keeping error messages readable.
func formatNumber(f float64) string {
	if f == math.Trunc(f) && !math.IsInf(f, 0) && !math.IsNaN(f) {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%g", f)
}
